spring:
  application:
    name: push
  datasource:
      url: jdbc:mysql://localhost:3306/push_server?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

firebase:
  service-account-key: classpath:firebase-service-account.json

apns:
  key-id: 7GAN6ZZ8Z8            # Apple .p8 Key ID
  team-id: V55RYE9J7R          # Apple Team ID
  key-file: classpath:apns-key.p8
  bundle-id: com.samanthena.flutterNotification  # 你的 App Bundle ID
  production: false              # 开发阶段用 false，上线改 true